version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kVi6
      POSTGRES_DB: API
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    networks:
      - internal
    expose:
      - "5432"

  mongodb:
    image: mvertes/alpine-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: kVi6
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    networks:
      - internal
    expose:
      - "27017"

  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - internal
    volumes:
      - backend-data:/app/data
    depends_on:
      - mongodb
      - postgres

  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend



volumes:
  postgres_data:
  mongo_data:
  backend-data:

networks:
  internal:
    driver: bridge
