version: "3.8"

services:
  mongo:
    image: /mongo-alpine
    container_name: mongodb
    volumes:
      - mongo-data:/data/mongo
    ports:
      - "27017:27017"
    networks:
      - internal
  
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - internal
    volumes:
      - backend-data:/app/data
    depends_on:
      - mongo
      - postgres
      - rabbit
    
  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    
  rabbit:
    image: rabbit:management-alpine
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
  
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres
    networks:
      - internal
    
volumes:
  postgres-data:
  mongo-data:
  backend-data:

networks:
  internal:
    driver: bridge