version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    working_dir: /app
    command: ["bash", "-c", "alembic upgrade head && uvicorn src.API.main:app --host 0.0.0.0 --port 8000 --workers 4"]
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 56730912xz
      POSTGRES_DB: API
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
