"""empty message

Revision ID: d9bcabfe9e21
Revises: 1856a0aa4a99
Create Date: 2025-04-23 16:24:51.281791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bcabfe9e21'
down_revision: Union[str, None] = '1856a0aa4a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bot', sa.Column('ads_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bot', 'ads_delay')
    # ### end Alembic commands ###
