"""empty message

Revision ID: 6a3bfa17e133
Revises: fed144f35ad4
Create Date: 2025-04-04 14:14:01.034113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a3bfa17e133'
down_revision: Union[str, None] = 'fed144f35ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bot', sa.Column('text', sa.String(), nullable=True))
    op.alter_column('Bot', 'nicknames',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bot', 'nicknames',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.drop_column('Bot', 'text')
    # ### end Alembic commands ###
